# Nim wrapper of 0mq
# Generated by c2nim with modifications and enhancement
# from Andreas Rumpf, Erwan Ameil
# Generated from zmq version 4.2.0
# Original licence follows:

#
#    Copyright (c) 2007-2013 Contributors as noted in zeromq's AUTHORS file
#
#    This file is part of 0MQ.
#
#    0MQ is free software; you can redistribute it and/or modify it under
#    the terms of the GNU Lesser General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    0MQ is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

## Nim 0mq wrapper. This file contains the low level C wrappers as well as
## some higher level constructs. The higher level constructs are easily
## recognizable because they are the only ones that have documentation.
##
## Example of a client:
##
## .. code-block:: nim
##   import zmq
##
##   var requester = zmq.connect("tcp://localhost:5555")
##   echo("Connecting...")
##   for i in 0..10:
##     echo("Sending hello... (" & $i & ")")
##     send(requester, "Hello")
##     var reply = receive(requester)
##     echo("Received: ", reply)
##   close(requester)
##
## Example of a server:
##
## .. code-block:: nim
##
##   import zmq
##   var responder = zmq.listen("tcp://*:5555")
##   while true:
##     var request = receive(responder)
##     echo("Received: ", request)
##     send(responder, "World")
##   close(responder)

import zmq/bindings
export bindings
import zmq/connections
export connections
import zmq/poller
export poller
import zmq/sockopt
export sockopt

